---
title: "HomeworkWeek6"
output:
  html_document:
    df_print: paged
---


## Loading in data
```{r}
{
  mygenes<- read.table(file = 'gene_dist_head.tsv', sep = '\t', header = TRUE)
  library('ggplot2')
  library('plotly')
}
```
## Summarize data
```{r}
summary(mygenes)
```

## Create a subset based on autosomes, and plot with the x-axis as chromosomes
```{r}
library(ggplot2) # We load in libraries
library(plotly)
# We define a factor set of autosomes
autosomes<-c("1","2","3","4","5","6","7","8","9","10",
 "11","12","13","14","15","16","17","18","19","20","21","22")  
# We create a new dataframe called 'genes' which only has autosomes, however we still have those additional factors
genes<- mygenes[ which(mygenes$chr %in% autosomes), ] 
# We remove the factors and then order them so they are numerical order and not alphabetical
genes$chr <- factor(genes$chr, levels = autosomes) 
 # We plot in ggplot 
ggplot(data = genes) +  geom_bar(mapping = aes(x = chr, fill = feature), width = 1)
```

## Plot the polar coordinates
```{r}
ggplot(data = genes) +
 geom_bar(mapping = aes(x = chr, fill = feature), width = 1) +
 coord_polar()
```

## Make bar graph interactive using ggplotly in the plotly library
```{r}
library(ggplot2)
library(plotly)
p<-ggplot(data = genes) +  geom_bar(mapping = aes(x = chr, fill = feature), width = 1)
ggplotly(p)
```


